// frontend/src/components/HistoryPage.jsx
// ─────────────────────────────────────────────────────────────────
//  Task 1: Dedicated upload history page
//  Task 2: Export Excel / PDF buttons per row
// ─────────────────────────────────────────────────────────────────
import { useState, useEffect } from "react";
import { getUploadHistory, exportExcel, exportPdf } from "../utils/api";
import "./HistoryPage.css";

function formatDate(iso) {
  return new Date(iso).toLocaleDateString("vi-VN", {
    year:   "numeric",
    month:  "short",
    day:    "numeric",
    hour:   "2-digit",
    minute: "2-digit",
  });
}

function parseResult(raw) {
  if (!raw) return null;
  try {
    return typeof raw === "string" ? JSON.parse(raw) : raw;
  } catch {
    return null;
  }
}

/** Trigger a browser download from a Blob */
function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export default function HistoryPage({ onBack }) {
  const [history,    setHistory]    = useState([]);
  const [loading,    setLoading]    = useState(true);
  const [error,      setError]      = useState(null);
  const [exporting,  setExporting]  = useState({}); // { [id]: "excel"|"pdf" }

  useEffect(() => {
    loadHistory();
  }, []);

  async function loadHistory() {
    setLoading(true);
    setError(null);
    try {
      const { history } = await getUploadHistory();
      setHistory(history);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  // ── Export handlers (Task 2) ──────────────────────────────────
  async function handleExport(item, format) {
    const result = parseResult(item.result);
    const payload = {
      file_name: item.file_name,
      result: {
        ...result,
        upload_time: item.upload_time,
      },
      // solution will be auto-generated by backend if missing
    };

    setExporting((prev) => ({ ...prev, [item.id]: format }));

    try {
      let blob;
      if (format === "excel") {
        blob = await exportExcel(payload);
        downloadBlob(blob, `${item.file_name}-report.xlsx`);
      } else {
        blob = await exportPdf(payload);
        downloadBlob(blob, `${item.file_name}-report.pdf`);
      }
    } catch (err) {
      alert(`Export failed: ${err.message}`);
    } finally {
      setExporting((prev) => {
        const next = { ...prev };
        delete next[item.id];
        return next;
      });
    }
  }

  return (
    <div className="history-page">
      {/* Header bar */}
      <div className="hp-header">
        <button className="hp-back" onClick={onBack} title="Back to main">
          ← Back
        </button>
        <h1 className="hp-title">Upload History</h1>
        <button
          className="hp-refresh"
          onClick={loadHistory}
          disabled={loading}
        >
          {loading ? "Loading…" : "↺ Refresh"}
        </button>
      </div>

      {/* Error state */}
      {error && (
        <div className="hp-error">
          <span className="hp-error-icon">⚠</span>
          <span>{error}</span>
        </div>
      )}

      {/* Loading state */}
      {loading && !error && (
        <div className="hp-loading">
          <div className="hp-spinner" />
          <p>Loading history…</p>
        </div>
      )}

      {/* Empty state */}
      {!loading && !error && history.length === 0 && (
        <div className="hp-empty">
          <div className="hp-empty-icon">📂</div>
          <h2>No uploads yet</h2>
          <p>Upload a document to see your history here.</p>
        </div>
      )}

      {/* Table */}
      {!loading && !error && history.length > 0 && (
        <div className="hp-table-wrap">
          <table className="hp-table" id="upload-history-table">
            <thead>
              <tr>
                <th>#</th>
                <th>File Name</th>
                <th>Upload Time</th>
                <th>Result</th>
                <th>Export</th>
              </tr>
            </thead>
            <tbody>
              {history.map((item, idx) => {
                const result = parseResult(item.result);
                const isExporting = exporting[item.id];
                return (
                  <tr key={item.id} className="hp-row">
                    <td className="hp-cell-num">{idx + 1}</td>
                    <td className="hp-cell-name" title={item.file_name}>
                      <div className="hp-file-info">
                        <span className="hp-file-icon">📄</span>
                        <span className="hp-file-name">{item.file_name}</span>
                      </div>
                    </td>
                    <td className="hp-cell-time">
                      {formatDate(item.upload_time)}
                    </td>
                    <td className="hp-cell-result">
                      {result ? (
                        <div className="hp-result-chips">
                          <span className="hp-chip hp-chip-fp">
                            {result.fp} FP
                          </span>
                          <span className="hp-chip hp-chip-effort">
                            {result.effort} PM
                          </span>
                          <span className="hp-chip hp-chip-cost">
                            ${Number(result.cost).toLocaleString()}
                          </span>
                        </div>
                      ) : (
                        <span className="hp-no-result">—</span>
                      )}
                    </td>
                    <td className="hp-cell-export">
                      <div className="hp-export-btns">
                        <button
                          className="hp-export-btn hp-export-excel"
                          onClick={() => handleExport(item, "excel")}
                          disabled={!!isExporting}
                          title="Export as Excel"
                          id={`export-excel-${item.id}`}
                        >
                          {isExporting === "excel" ? (
                            <span className="hp-btn-spinner" />
                          ) : (
                            <>📊 Excel</>
                          )}
                        </button>
                        <button
                          className="hp-export-btn hp-export-pdf"
                          onClick={() => handleExport(item, "pdf")}
                          disabled={!!isExporting}
                          title="Export as PDF"
                          id={`export-pdf-${item.id}`}
                        >
                          {isExporting === "pdf" ? (
                            <span className="hp-btn-spinner" />
                          ) : (
                            <>📕 PDF</>
                          )}
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* Footer summary */}
      {!loading && !error && history.length > 0 && (
        <div className="hp-footer">
          <span className="hp-count">
            {history.length} upload{history.length !== 1 ? "s" : ""} total
          </span>
        </div>
      )}
    </div>
  );
}
